name: Lint

on:
  - pull_request
  - workflow_dispatch

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  mypy:
    runs-on: ubuntu-latest
    steps:
      # or specify a path!
      - uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: '--explicit-package-bases'
          path: 'eflips'